<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-25T13:14:46 IST" name="Suite" finished-at="2024-01-25T13:15:15 IST" duration-ms="28612">
    <groups>
    </groups>
    <test started-at="2024-01-25T13:14:46 IST" name="Test" finished-at="2024-01-25T13:15:15 IST" duration-ms="28612">
      <class name="TestScenarios.TestCases">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestScenarios.TestCases@36902638]" started-at="2024-01-25T13:14:46 IST" name="setup" finished-at="2024-01-25T13:14:54 IST" duration-ms="7419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="searchOperations()[pri:0, instance:TestScenarios.TestCases@36902638]" started-at="2024-01-25T13:14:54 IST" name="searchOperations" finished-at="2024-01-25T13:14:56 IST" duration-ms="2554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchOperations -->
        <test-method signature="verifyAndAccessFacebook()[pri:0, instance:TestScenarios.TestCases@36902638]" started-at="2024-01-25T13:14:56 IST" name="verifyAndAccessFacebook" finished-at="2024-01-25T13:15:00 IST" duration-ms="3700" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAndAccessFacebook -->
        <test-method signature="verifyLogin()[pri:0, instance:TestScenarios.TestCases@36902638]" started-at="2024-01-25T13:15:00 IST" name="verifyLogin" finished-at="2024-01-25T13:15:15 IST" duration-ms="14649" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login page] but found [Log in to Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login page] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Objects.FaceBookPage.verifyLoging(FaceBookPage.java:35)
at TestScenarios.TestCases.verifyLogin(TestCases.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="clear()[pri:0, instance:TestScenarios.TestCases@36902638]" started-at="2024-01-25T13:15:15 IST" name="clear" finished-at="2024-01-25T13:15:15 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
      </class> <!-- TestScenarios.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
